spring:
  application.name: avro-producer
  kafka:
    bootstrap-servers: localhost:9092
#    producer:
#      properties:
#        value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
  cloud:
    stream:
      schema-registry-client.endpoint: http://localhost:8071
      schema.avro.dynamic-schema-generation-enabled: true
      kafka:
        binder:
          brokers: ${spring.kafka.bootstrap-servers}
#        bindings:
#          test-request:
#            producer:
#              configuration:
#                value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      bindings:
        test-request:
          destination: test-request
          contentType: application/*+avro
#          producer:
#            configuration:
#              value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
#            use-native-encoding: true
logging.level:
  com.wilkins: debug
server.port: 8101