spring:
  application.name: avro-consumer
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: avro-consumer
#      use-native-decoding: true
#      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
#      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: com.wilkins.avro.consumer.MessageDeserializer
      properties:
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
        auto.offset.reset: latest
        enable.auto.commit: true
  cloud:
    stream:
      schema-registry-client.endpoint: http://localhost:8071
logging.level:
  com.wilkins: debug
server:
  port: 8082